#:schema https://raw.githubusercontent.com/astral-sh/uv/refs/heads/main/uv.schema.json

# https://docs.astral.sh/uv/reference/settings
check-url = "https://pypi.org/simple"
publish-url = "https://upload.pypi.org/legacy/"
compile-bytecode = true
index-strategy = "unsafe-best-match"
link-mode = "copy"
system-certs = true
no-binary = false
offline = false
prerelease = "if-necessary-or-explicit"
preview = true

# https://docs.astral.sh/uv/reference/settings/#index
[[index]]
name = "default"
url = "https://pypi.org/simple"
default = true

[pip]
universal = true
annotation-style = "line"
output-file = "requirements.txt"
