#:schema https://raw.githubusercontent.com/astral-sh/uv/refs/heads/main/uv.schema.json
# Example: https://docs.astral.sh/uv/reference/settings/#configuration

check-url = "https://pypi.org/simple"
publish-url = "https://upload.pypi.org/legacy/"
compile-bytecode = true
# concurrent-builds = 4
# concurrent-downloads = 4
# concurrent-installs = 4
index-strategy = "first-index"
system-certs = false
offline = false
prerelease = "if-necessary"
preview-features = true

# https://docs.astral.sh/uv/reference/settings/#index
[[index]]
name = "default"
url = "https://pypi.org/simple"
default = true

[pip]
universal = true
annotation-style = "split"
compile-bytecode = true
index-url = "https://pypi.org/simple"
output-file = "requirements.txt"
prerelease = "if-necessary"
